### ISSUE TITLE
Ширина слоев торта

### ISSUE THREAD

**Issue by elaman** [Aiperi-Amankulova/cake-builder#1]
Изменить картинки .svg, так чтобы слои тортов были шире.

**Comment by elaman** [comment]
Чтобы слой был по середине нужно использовать `background-position` свойство.

**Comment by Aiperi-Amankulova** [comment]
хорошо

**Comment by Aiperi-Amankulova** [comment]
агай получилось)

**Comment by elaman** [comment]
Молодец, теперь картинки поменяй

**Comment by elaman** [comment]
@Aiperi-Amankulova  Не вижу прогресса

**Comment by Aiperi-Amankulova** [comment]
Я картинки по шире сделать не могу (

**Comment by elaman** [comment]
Постарайся

**Comment by Aiperi-Amankulova** [comment]
Эламан агай, а что если css тарелку поменять на вазу для тортов.  Как думаете она много места занимать будет?

**Comment by elaman** [comment]
@Aiperi-Amankulova не думаю. Если ты сделаешь слои тоньше и сделаешь, чтобы высота Cake компонента увеличивалось, точно поместится.

**Comment by Aiperi-Amankulova** [comment]
Вроде бы получилось.
